apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "prisma-ha.fullname" . }}
  labels:
    {{- include "prisma-ha.labels" . | nindent 4 }}
data:
  config: |
    port: 4466
    {{- if .Values.api.enabled }}
    enableManagementApi: true
    {{- else }}
    enableManagementApi: false
    {{- end }}
    {{- if .Values.api.auth }}
    managementApiSecret: $PRISMA_API_SECRET
    {{- end }}
    {{- if .Values.messaging.enabled }}
    rabbitUri: $PRISMA_RABBIT_URI
    {{- end }}
    databases:
      default:
        connector: $PRISMA_DB_CONNECTOR
        host: $PRISMA_DB_HOST
        port: $PRISMA_DB_PORT
        user: $PRISMA_DB_USER
        password: $PRISMA_DB_PASSWORD
        migrations: $PRISMA_DB_MIGRATIONS
        database: $PRISMA_DB_NAME
        {{- if eq .Values.database.connector "postgres" }}
        schema: $PRISMA_DB_SCHEMA
        {{- end }}
        ssl: $PRISMA_DB_SSL
        connectionLimit: $PRISMA_DB_CONNECTIONLIMIT
        {{- if .Values.database.raw }}
        rawAccess: true
        {{- else }}
        rawAccess: false
        {{- end }}
