apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prisma-ha.fullname" . }}
  labels:
    app: {{ template "prisma-ha.name" . }}
    chart: {{ template "prisma-ha.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  pubsub-uri: {{ include "prisma-ha.messaging.uri" . | b64enc | quote }}
  {{- if and .Values.api.auth .Values.api.secret }}
  api-secret: {{ .Values.api.secret | b64enc | quote }}
  {{- else if .Values.api.auth }}
  api-secret: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
  db-user: {{ .Values.database.user | b64enc | quote }}
  {{- if not .Values.postgresql.enabled }}
  {{- if .Values.database.password }}
  db-password: {{ .Values.database.password | b64enc | quote }}
  {{- else }}
  db-password: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
  {{- end }}
