apiVersion: v1
kind: Service
metadata:
  name: {{ include "prisma-ha.fullname" . }}
  labels:
    {{- include "prisma-ha.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: service
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: prisma
  selector:
    app: {{ template "prisma-ha.name" . }}
    release: {{ .Release.Name }}
